/** Node.js build plugin. Produces a Hono HTTP server with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	// Node has no platform-provided bundler — esbuild is our final-output
	// step here, producing a single self-contained `dist/server.mjs`.
	bundle = 'esbuild' as const;

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers. We register every
		// agent — including trigger-less ones — in the handler map so that the
		// CLI's `flue run` can invoke them in local mode. The webhookAgents
		// set below gates which are reachable over public HTTP when deployed.
		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Build the handler map — includes ALL agents, not just webhook ones.
		const handlerMapEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');

		// Build webhook agent names set — used to gate the public HTTP route.
		const webhookNames = JSON.stringify(webhookAgents.map((a) => a.name));

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		return `
// Auto-generated by @flue/sdk build (node)
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { serve } from '@hono/node-server';
import { Bash, InMemoryFs, MountableFs, ReadWriteFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  bashFactoryToSessionEnv,
  resolveModel,
  parseJsonBody,
  validateAgentRequest,
  toHttpResponse,
  toSseData,
  RouteNotFoundError,
} from '@flue/sdk/internal';
import { randomUUID } from 'node:crypto';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const roles = ${rolesJson};
const systemPrompt = '';

const handlers = {
${handlerMapEntries}
};

// Set of webhook-accessible agent names. Named distinctly from the
// validateAgentRequest \`webhookAgents\` parameter to keep the call site
// below readable.
const webhookAgentSet = new Set(${webhookNames});

// When the CLI starts this server via \`flue run\`, it sets FLUE_MODE=local.
// In local mode the HTTP route accepts any registered agent (including
// trigger-less CI-only agents). In any other mode the route is restricted to
// agents with \`webhook: true\`, preventing accidental public exposure of
// agents that the user only intended to invoke from their CI pipeline.
const isLocalMode = process.env.FLUE_MODE === 'local';

const manifest = ${manifest};

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * Create a local sandbox backed by the host filesystem.
 * Mounts process.cwd() at /workspace via ReadWriteFs + MountableFs.
 */
async function createLocalEnv() {
  const rwfs = new ReadWriteFs({ root: process.cwd() });
  const fs = new MountableFs({ base: new InMemoryFs() });
  fs.mount('/workspace', rwfs);
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    cwd: '/workspace',
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();

function createContextForRequest(id, payload, req) {
  return createFlueContext({
    id,
    payload,
    env: process.env,
    req,
    agentConfig: {
      systemPrompt, skills, roles, model: undefined, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
  });
}

// ─── Server ─────────────────────────────────────────────────────────────────

const app = new Hono();

app.get('/health', (c) => c.json({ status: 'ok' }));
app.get('/agents', (c) => c.json(manifest));

// Catch any method on the agent route so non-POSTs become 405 (instead of
// Hono's default 404 for unmatched method). Throws are translated by the
// onError handler into the canonical error envelope.
app.all('/agents/:name/:id', async (c) => {
  const name = c.req.param('name');
  const id = c.req.param('id');

  // Validate method, name shape, registration, webhook-accessibility.
  // Throws FlueHttpError on any failure; caught by app.onError below.
  validateAgentRequest({
    method: c.req.method,
    name,
    id,
    registeredAgents: Object.keys(handlers),
    webhookAgents: Array.from(webhookAgentSet),
    allowNonWebhook: isLocalMode,
  });

  const handler = handlers[name];

  // Parse the request body. Throws on invalid Content-Type or malformed JSON;
  // returns {} for genuinely empty bodies (so no-payload agents still work).
  const payload = await parseJsonBody(c.req.raw);

  const accept = c.req.header('accept') || '';
  const isWebhook = c.req.header('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  // Fire-and-forget (webhook mode)
  if (isWebhook) {
    const requestId = randomUUID();
    const ctx = createContextForRequest(id, payload, c.req.raw);
    handler(ctx).then(
      (result) => {
        ctx.setEventCallback(undefined);
        console.log('[flue] Webhook handler complete:', name, result !== undefined ? JSON.stringify(result) : '(no return)');
      },
      (err) => {
        ctx.setEventCallback(undefined);
        console.error('[flue] Webhook handler error:', name, err);
      },
    );
    return c.json({ status: 'accepted', requestId }, 202);
  }

  // SSE streaming mode. Two error regimes meet here:
  //   - Pre-stream errors (validation, body parsing, agent lookup) have
  //     already thrown above and are rendered as plain HTTP responses by
  //     app.onError — headers haven't been sent yet, so this works.
  //   - Errors during agent execution surface as in-stream \`error\` events
  //     with the canonical envelope (via toSseData), since by then the
  //     200 + text/event-stream headers are already on the wire.
  if (isSSE) {
    return streamSSE(c, async (stream) => {
      let eventId = 0;
      let isIdle = false;
      const ctx = createContextForRequest(id, payload, c.req.raw);
      ctx.setEventCallback((event) => {
        if (event.type === 'idle') isIdle = true;
        stream.writeSSE({ data: JSON.stringify(event), event: event.type, id: String(eventId++) }).catch(() => {});
      });

      // Keep long-running, otherwise-idle SSE streams alive.
      const heartbeat = setInterval(() => {
        stream.write(': heartbeat\\n\\n').catch(() => {});
      }, 25_000);

      try {
        const result = await handler(ctx);
        if (!isIdle) {
          const idle = { type: 'idle' };
          await stream.writeSSE({ data: JSON.stringify(idle), event: 'idle', id: String(eventId++) });
        }
        await stream.writeSSE({
          data: JSON.stringify({ type: 'result', data: result !== undefined ? result : null }),
          event: 'result',
          id: String(eventId++),
        });
      } catch (err) {
        await stream.writeSSE({
          data: toSseData(err),
          event: 'error',
          id: String(eventId++),
        });
        if (!isIdle) {
          const idle = { type: 'idle' };
          await stream.writeSSE({ data: JSON.stringify(idle), event: 'idle', id: String(eventId++) });
        }
      } finally {
        clearInterval(heartbeat);
        ctx.setEventCallback(undefined);
      }
    });
  }

  // Sync mode (default). Errors propagate to app.onError.
  const ctx = createContextForRequest(id, payload, c.req.raw);
  try {
    const result = await handler(ctx);
    return c.json({ result: result !== undefined ? result : null });
  } finally {
    ctx.setEventCallback(undefined);
  }
});

// 404 handler — fires for any URL that didn't match a registered route.
app.notFound((c) => {
  // Throw rather than return so the onError handler is the single source of
  // truth for error-envelope shaping.
  throw new RouteNotFoundError({ method: c.req.method, path: new URL(c.req.url).pathname });
});

// Single-source-of-truth error renderer. Every thrown FlueError (and every
// thrown unknown) is converted to the canonical JSON envelope here.
// toHttpResponse takes care of logging unknowns — no extra console.error
// needed at this layer.
app.onError((err) => toHttpResponse(err));

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({
  fetch: app.fetch,
  port,
  // SSE requests can outlive Node's default 300s request timeout.
  serverOptions: { requestTimeout: 0 },
});
console.log('[flue] Server listening on http://localhost:' + port);
if (isLocalMode) {
  console.log('[flue] Mode: local (all agents invokable, including trigger-less)');
  console.log('[flue] Available agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
} else {
  console.log('[flue] Available agents: ' + ${JSON.stringify(webhookAgents.map((a) => a.name).join(', '))});
}

process.on('SIGINT', () => { server.close(); process.exit(0); });
process.on('SIGTERM', () => { server.close(); process.exit(0); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
			// just-bash's archive code wraps these native addons in dynamic imports
			// inside try/catch and declares them as optionalDependencies. Externalize
			// so esbuild doesn't try to resolve them at bundle time — the failure
			// path is handled by just-bash at runtime with a clear error message.
			external: ['node-liblzma', '@mongodb-js/zstd'],
		};
	}
}

function agentVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'agent';
	return `handler_${readableName}_${index}`;
}
