packages: [ packages/*, examples/*, apps/* ]
allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  core-js-pure: false
  esbuild: false
  lmdb: true
  msgpackr-extract: true
  node-liblzma: false
  protobufjs: false
  # Required by Astro support in apps/www.
  sharp: true
  workerd: false
minimumReleaseAge: 1440
resolutionMode: highest
minimumReleaseAgeExclude:
  - '@aws-sdk/*'
  - '@smithy/*'
  - protobufjs
