/** Node.js build plugin. Produces a server for workflow runs and agent interactions. */
import {
	agentVarName,
	channelVarName,
	generateBuiltModuleNormalizationSource,
	workflowVarName,
} from './generated-entry-normalization.ts';
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	bundle: BuildPlugin['bundle'] = 'vite';

	generateEntryPoint(ctx: BuildContext): string {
		return `${this.generateRuntimeEntryPoint(ctx, { deployment: true })}
const lifecycle = await startFlueNodeServer({
  port: parseInt(process.env.PORT || '3000', 10),
  hostname: process.env.FLUE_INTERNAL_LOCAL_ONLY === '1' ? '127.0.0.1' : undefined,
  local: process.env.FLUE_MODE === 'local',
  internalDevLogs: process.env.FLUE_INTERNAL_DEV_LOGS === '1',
  onReady: () => process.send?.('flue:dev-ready'),
});
async function stop(exitCode) {
  setTimeout(() => {
    console.error('[flue] Shutdown timed out, exiting.');
    process.exit(exitCode);
  }, 60_000).unref();
  await lifecycle.stop();
  process.exit(exitCode);
}
process.on('SIGINT', () => { void stop(130); });
process.on('SIGTERM', () => { void stop(143); });
process.on('disconnect', () => { void stop(0); });
`;
	}

	generateRuntimeEntryPoint(ctx: BuildContext, options: { deployment?: boolean } = {}): string {
		const { agents, appEntry, channels, dbEntry, workflows } = ctx;
		const runtimeVersion = JSON.stringify(ctx.runtimeVersion);
		const temporaryLocalExposure = JSON.stringify(ctx.temporaryLocalExposure);

		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				return `import * as ${varName} from ${JSON.stringify(a.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');

		const workflowImports = workflows
			.map((workflow, index) => {
				const varName = workflowVarName(workflow.name, index);
				return `import * as ${varName} from ${JSON.stringify(workflow.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');
		const channelImports = channels
			.map((channel, index) => {
				const varName = channelVarName(channel.name, index);
				return `import * as ${varName} from ${JSON.stringify(channel.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');

		const agentModuleEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');
		const workflowModuleEntries = workflows
			.map(
				(workflow, index) =>
					`  ${JSON.stringify(workflow.name)}: ${workflowVarName(workflow.name, index)},`,
			)
			.join('\n');
		const channelModuleEntries = channels
			.map(
				(channel, index) =>
					`  ${JSON.stringify(channel.name)}: ${channelVarName(channel.name, index)},`,
			)
			.join('\n');

		// User-supplied app.ts (if any). The generated entry imports the user's
		// default export and dispatches all requests through `app.fetch`. When
		// no app.ts is present, the generated entry constructs a thin default
		// Hono that mounts `flue()` and renders canonical error envelopes.
		const userAppImport = appEntry
			? `import userApp from ${JSON.stringify(appEntry.replace(/\\/g, '/'))};`
			: '';
		const userDbImport = dbEntry
			? `import userPersistenceAdapter from ${JSON.stringify(dbEntry.replace(/\\/g, '/'))};`
			: '';

		// All HTTP routing, workflow admission, agent dispatch, and error
		// rendering live in @flue/runtime's runtime modules. The generated
		// entry's job is narrow: import handlers, build the runtime config,
		// instantiate sandboxes, start the listener.
		const packagedSkillsImport = `import { getPackagedSkills } from 'virtual:flue/packaged-skills';`;
		const packagedSkillsValue = 'getPackagedSkills()';
		const builtModuleNormalizationSource = generateBuiltModuleNormalizationSource();
		return `
// Auto-generated by flue (target: node)
${packagedSkillsImport}
${options.deployment ? "import createDebug from 'debug';" : ''}
import { AsyncLocalStorage } from 'node:async_hooks';
import { format } from 'node:util';
import { serve } from '@hono/node-server';
import { sqlite } from '@flue/runtime/node';
import {
  Bash,
  InMemoryFs,
  admitDetachedWorkflow,
  assertWorkflowDefinition,
  createFlueContext,
  createNodeAgentCoordinator,
  createNodeDispatchQueue,
  bashFactoryToSessionEnv,
  resolveModel,
  configureFlueRuntime,
  createDefaultFlueApp,
  installDevLifecycleLogger,
} from '@flue/runtime/internal';
${agentImports}
${workflowImports}
${channelImports}
${userAppImport}
${userDbImport}

// ─── Config ─────────────────────────────────────────────────────────────────

const packagedSkills = ${packagedSkillsValue};
const debugStartup = typeof createDebug === 'function'
  ? createDebug('flue:server:startup')
  : () => {};

${builtModuleNormalizationSource}
const agentModules = {
${agentModuleEntries}
};
const workflowModules = {
${workflowModuleEntries}
};
const channelModules = {
${channelModuleEntries}
};
const normalized = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const { agents, workflows, channelHandlers } = normalized;

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

export async function startFlueNodeServer(options = {}) {
  const runtimeEnv = options.env ?? process.env;
  const isLocalMode = options.local === true;
  const outputContext = new AsyncLocalStorage();
  const originalConsole = new Map();
  let outputRestored = false;
  const restoreOutput = () => {
    if (outputRestored) return;
    outputRestored = true;
    for (const [method, original] of originalConsole) console[method] = original;
  };
  if (options.onOutput) {
    for (const method of ['log', 'info', 'debug', 'warn', 'error']) {
      const original = console[method];
      originalConsole.set(method, original);
      console[method] = (...args) => {
        if (!outputContext.getStore()) return original.apply(console, args);
        outputContext.exit(() => options.onOutput({
          stream: method === 'warn' || method === 'error' ? 'stderr' : 'stdout',
          line: format(...args),
        }));
      };
    }
  }
  const runInRuntime = (fn) => outputContext.run(true, fn);
  try {
  return await runInRuntime(async () => {
  const devLifecycle = isLocalMode && options.internalDevLogs === true ? installDevLifecycleLogger() : undefined;
${
	dbEntry
		? `// Custom persistence from db.ts. connect() is awaited once at startup so
// an unreachable or misconfigured database fails at boot, not inside the
// first request.
if (!userPersistenceAdapter || typeof userPersistenceAdapter.connect !== 'function') {
  throw new Error('[flue] db.ts must default-export a PersistenceAdapter with a connect() method.');
}
let executionStore;
let runStore;
let eventStreamStore;
try {
  if (userPersistenceAdapter.migrate) await userPersistenceAdapter.migrate();
  const stores = await userPersistenceAdapter.connect();
  if (!stores || typeof stores !== 'object') {
    throw new Error('connect() must return { executionStore, runStore, eventStreamStore }.');
  }
  ({ executionStore, runStore, eventStreamStore } = stores);
  if (!executionStore || typeof executionStore.sessions?.save !== 'function' || typeof executionStore.submissions?.getSubmission !== 'function') {
    throw new Error('connect() must return an executionStore with sessions and submissions.');
  }
  if (!runStore || typeof runStore.createRun !== 'function' || typeof runStore.listRuns !== 'function') {
    throw new Error('connect() must return a runStore.');
  }
  if (!eventStreamStore || typeof eventStreamStore.appendEvent !== 'function' || typeof eventStreamStore.readEvents !== 'function') {
    throw new Error('connect() must return an eventStreamStore.');
  }
} catch (error) {
  throw new Error('[flue] Failed to initialize persistence from db.ts: ' + (error instanceof Error ? error.message : error), { cause: error });
}`
		: `// Default persistence for Node — in-memory SQLite, process lifetime.
const defaultAdapter = sqlite();
if (defaultAdapter.migrate) await defaultAdapter.migrate();
const { executionStore, runStore, eventStreamStore } = await defaultAdapter.connect();`
}
const persistenceAdapter = ${dbEntry ? `userPersistenceAdapter` : `defaultAdapter`};
const agentCoordinator = createNodeAgentCoordinator({
  submissions: executionStore.submissions,
  sessions: executionStore.sessions,
  agents,
  createContext: createAgentContextForRequest,
  eventStreamStore,
  onInteractionStart: devLifecycle?.onAgentInteractionStart,
});
const dispatchQueue = createNodeDispatchQueue(agentCoordinator);

function createAgentContextForRequest({ id, request, initialEventIndex, dispatchId }) {
  return createFlueContext({
    id,
    dispatchId,
    initialEventIndex,
    env: runtimeEnv,
    req: request,
    agentConfig: { packagedSkills, resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

function createWorkflowContextForRequest({ runId, request, initialEventIndex }) {
  return createFlueContext({
    id: runId,
    runId,
    initialEventIndex,
    env: runtimeEnv,
    req: request,
    agentConfig: { packagedSkills, resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

// ─── Runtime seed ───────────────────────────────────────────────────────────

// Seed the public flue() sub-app with everything it needs to dispatch agent
// requests in-process. Must run before \`flue()\` handles any request — by
// virtue of being a top-level statement, it executes before \`serve(...)\`
// below binds the listener. User app.ts files that call \`flue()\` at top
// level are also fine because Hono routes are lazy: they read this config
// only when a request arrives.
configureFlueRuntime({
  target: 'node',
  devMode: isLocalMode,
  temporaryLocalExposure: ${temporaryLocalExposure},
  runtimeVersion: ${runtimeVersion},
  agents,
  workflows,
  createAgentAdmission: (agentName, instanceId) =>
    agentCoordinator.createAdmission(agentName, instanceId),
  dispatchQueue,
  admitWorkflow: ({ workflowName, input }) => {
    const workflow = workflows.find((record) => record.name === workflowName)?.definition;
    if (!workflow) throw new Error('[flue] Internal workflow admission target is not registered.');
    return admitDetachedWorkflow({
      workflowName,
      workflow,
      input,
      request: new Request('https://flue.invalid/_internal/workflows/' + encodeURIComponent(workflowName), { method: 'POST' }),
      createContext: createWorkflowContextForRequest,
      runStore,
      eventStreamStore,
    });
  },
  channelHandlers,
  createWorkflowContext: createWorkflowContextForRequest,
  runStore,
  eventStreamStore,
});

// Reconcile any interrupted submissions from a previous process.
// This is best-effort on startup — errors are logged but do not block the server.
runInRuntime(() => agentCoordinator.reconcileSubmissions()).catch((error) => {
  runInRuntime(() => console.error('[flue] Startup submission reconciliation failed:', error));
});

// ─── App composition ────────────────────────────────────────────────────────

${
	appEntry
		? `// User-supplied app.ts: their default export owns the entire request
// pipeline. We just verify it exposes a fetch method and pass the
// listener through. flue() is available for them to mount, but the
// composition is theirs to author.
const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request) method.'
  );
}`
		: `// No app.ts: build the default app via @flue/runtime so the generated entry
// stays \`hono\`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts \`flue()\` at root
// and renders canonical Flue envelopes for unmatched paths.
const flueApp = createDefaultFlueApp();`
}

// ─── Start ──────────────────────────────────────────────────────────────────

  const port = options.port ?? 3000;
  let resolveReady;
  let rejectReady;
  const ready = new Promise((resolve, reject) => {
    resolveReady = resolve;
    rejectReady = reject;
  });
  const server = serve({
    fetch: (request, env) => runInRuntime(() => flueApp.fetch(request, env)),
    port,
    ...(options.hostname ? { hostname: options.hostname } : {}),
    serverOptions: { requestTimeout: 0 },
  }, () => {
    if (!options.quiet) console.log('[flue] Server listening on http://localhost:' + port);
    if (isLocalMode) debugStartup('mode=local');
    debugStartup('agents=%s', ${JSON.stringify(agents.map((a) => a.name).join(', '))});
    options.onReady?.();
    resolveReady();
  });
  const onServerError = (error) => rejectReady(error);
  const onAbort = () => {
    server.closeAllConnections();
    server.close();
    rejectReady(options.signal?.reason ?? new DOMException('Aborted', 'AbortError'));
  };
  server.once('error', onServerError);
  options.signal?.addEventListener('abort', onAbort, { once: true });
  if (options.signal?.aborted) onAbort();
  try {
    await ready;
  } catch (error) {
    server.closeAllConnections();
    server.close();
    throw error;
  } finally {
    server.off('error', onServerError);
    options.signal?.removeEventListener('abort', onAbort);
  }
  let shuttingDown;
  return {
    async stop() {
      if (shuttingDown) return shuttingDown;
      shuttingDown = runInRuntime(async () => {
        const errors = [];
        const httpClosed = new Promise((resolve) => server.close((error) => {
          if (error) errors.push(error);
          resolve();
        }));
        try {
          await agentCoordinator.shutdown();
        } catch (error) {
          errors.push(error);
        }
        try {
          if (persistenceAdapter.close) await persistenceAdapter.close();
        } catch (error) {
          errors.push(error);
        }
        server.closeAllConnections();
        await httpClosed;
        restoreOutput();
        if (errors.length === 1) throw errors[0];
        if (errors.length > 1) throw new AggregateError(errors, '[flue] Node server shutdown failed.');
      });
      return shuttingDown;
    },
    closeSync() {
      server.closeAllConnections();
      server.close();
      restoreOutput();
    },
  };
  });
  } catch (error) {
    restoreOutput();
    throw error;
  }
}
`;
	}

	external = ['node-liblzma', '@mongodb-js/zstd'];
}
