/** Cloudflare build plugin. Produces a Worker + DO entry point with SSE/webhook/sync modes. */
import * as path from 'node:path';
import {
	assertSandboxPackageInstalled,
	computeFlueMigrations,
	detectSandboxBindings,
	type FlueAdditions,
	mergeFlueAdditions,
	readUserWranglerConfig,
	stripNoisyWranglerDefaults,
	validateUserWranglerConfig,
	writeDeployRedirectIfMissing,
} from './cloudflare-wrangler-merge.ts';
import type { BuildContext, BuildPlugin } from './types.ts';

export class CloudflarePlugin implements BuildPlugin {
	name = 'cloudflare';
	// Skip Flue's esbuild pass: wrangler bundles the entry itself, both for
	// `wrangler dev` and `wrangler deploy`. Pre-bundling caused subtle
	// resolution conflicts with `nodejs_compat` (e.g. `tar` package using
	// bare `fs`/`zlib`/`assert` imports). Letting wrangler be the only
	// bundler in the chain eliminates that whole category of problem and
	// makes our dev/deploy paths identical.
	bundle = 'none' as const;
	entryFilename = '_entry.ts';

	/**
	 * Per-build cache of the user's wrangler config. Both `generateEntryPoint`
	 * and `additionalOutputs` need it (for sandbox detection + the merge), and
	 * a fresh `CloudflarePlugin` instance is constructed for each build (see
	 * `resolvePlugin` in build.ts), so the cache is implicitly scoped to a
	 * single build.
	 */
	private userConfigCache: Awaited<ReturnType<typeof readUserWranglerConfig>> | undefined;

	/**
	 * Read the user's wrangler config from `root`. The user's config always
	 * lives at the project root, regardless of where the build artifacts get
	 * written via `output`. We only re-locate the *generated*
	 * `wrangler.jsonc` (the merged one) — never the source one.
	 */
	private async getUserConfig(root: string) {
		if (!this.userConfigCache) {
			this.userConfigCache = await readUserWranglerConfig(root);
		}
		return this.userConfigCache;
	}

	async generateEntryPoint(ctx: BuildContext): Promise<string> {
		const { agents, roles, appEntry } = ctx;
		const rolesJson = JSON.stringify(roles);
		const manifestJson = JSON.stringify(ctx.manifest);
		const runtimeVersion = JSON.stringify(ctx.runtimeVersion);
		validateCloudflareAgentNames(ctx);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		const agentClasses = webhookAgents
			.map((a) => {
				const className = agentClassName(a.name);
				const handlerVar = agentVarName(a.name, agents.indexOf(a));
				return `export class ${className} extends Agent {
  async onRequest(request) {
    return dispatchAgent(request, this, ${JSON.stringify(a.name)}, ${handlerVar});
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:')) {
      return handleFlueFiberRecovered(ctx, this, ${JSON.stringify(a.name)});
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
}`;
			})
			.join('\n\n');

		const { config: userConfig } = await this.getUserConfig(ctx.root);
		const sandboxClassNames = detectSandboxBindings(userConfig);
		const sandboxReExports = sandboxClassNames
			.map((name) => `export { Sandbox as ${name} } from '@cloudflare/sandbox';`)
			.join('\n');

		const userAppImport = appEntry
			? `import userApp from '${appEntry.replace(/\\/g, '/')}';`
			: '';

		return `
// Auto-generated by flue (target: cloudflare)
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName, routeAgentRequest } from 'agents';
import { Bash, InMemoryFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  InMemoryRunStore,
  createDurableRunStore,
  createRunSubscriberRegistry,
  bashFactoryToSessionEnv,
  resolveModel,
  handleAgentRequest,
  handleRunRouteRequest,
  configureFlueRuntime,
  createDefaultFlueApp,
  hasRegisteredProvider,
} from '@flue/runtime/internal';
import {
  runWithCloudflareContext,
  cfSandboxToSessionEnv,
  getCloudflareAIBindingApiProvider,
  FlueRegistry,
  createCloudflareRunRegistry,
} from '@flue/runtime/cloudflare';
import { registerApiProvider, registerProvider } from '@flue/runtime/app';

${agentImports}

${userAppImport}

// ─── Internal provider registrations ────────────────────────────────────────
// User \`app.ts\` imports are hoisted above this body, so a user-supplied
// \`registerProvider('cloudflare', ...)\` runs first; the guard below
// preserves it. The default enables Cloudflare's default AI Gateway,
// which the binding spins up on demand for the account.

registerApiProvider(getCloudflareAIBindingApiProvider());

if (!hasRegisteredProvider('cloudflare')) {
  registerProvider('cloudflare', {
    api: 'cloudflare-ai-binding',
    binding: env.AI,
    gateway: { id: 'default' },
  });
}

// ─── Config ─────────────────────────────────────────────────────────────────

const roles = ${rolesJson};
const skills = {};
const systemPrompt = '';

const webhookAgentNames = ${JSON.stringify(webhookAgents.map((a) => a.name))};

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * Detect and wrap external sandbox instances (e.g. from @cloudflare/sandbox's
 * getSandbox()). Returns SessionEnv if the value looks like a Durable Object
 * RPC stub, null otherwise.
 *
 * NOTE on detection: The value returned by \`getSandbox()\` is a workerd RPC
 * Proxy. None of the obvious detection strategies work:
 *
 *   - Structural duck-typing (\`'X' in stub\`, \`typeof stub.X === 'function'\`):
 *     the proxy lies positively for any property name, so any check returns
 *     \`true\` regardless of what's actually on the remote.
 *   - \`instanceof <UserSandboxClass>\` (e.g. \`Sandbox\` from
 *     \`@cloudflare/sandbox\`): the user's class only exists on the in-DO
 *     side; over RPC the caller gets a generic stub.
 *   - \`instanceof DurableObject\` (imported from \`cloudflare:workers\`): the
 *     stub's prototype chain has a class *named* \`DurableObject\`, but it's a
 *     workerd-internal class with a different identity than the importable
 *     one. \`instanceof\` checks identity, not name, so it returns \`false\`.
 *
 * The one signal that does work — verified by runtime probe — is the string
 * name of the prototype's constructor. Workerd's internal RPC stub class is
 * named \`DurableObject\`, and \`Object.getPrototypeOf(stub).constructor.name\`
 * returns that string. This is a heuristic (it relies on a workerd-internal
 * naming convention, not a contractual API), but it's empirically correct
 * today and will misroute only if a user passes some other DO stub to
 * \`init({ sandbox })\` — in which case \`cfSandboxToSessionEnv\` will fail
 * loudly on first method call.
 */
function resolveSandbox(sandbox) {
  if (
    sandbox &&
    typeof sandbox === 'object' &&
    Object.getPrototypeOf(sandbox)?.constructor?.name === 'DurableObject'
  ) {
    return cfSandboxToSessionEnv(sandbox);
  }
  return null;
}

// Fallback in-memory store (used if no DO storage is available).
const memoryStore = new InMemorySessionStore();
const memoryRunStore = new InMemoryRunStore();

// Module-scoped per-isolate registry; run ids isolate buckets across DOs.
const runSubscribers = createRunSubscriberRegistry();

// Create a DO-backed session store from the Durable Object's SQL storage.
function createDOStore(sql) {
  // Ensure the table exists
  sql.exec(
    'CREATE TABLE IF NOT EXISTS flue_sessions (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at INTEGER NOT NULL)'
  );
  return {
    async save(id, data) {
      const json = JSON.stringify(data);
      sql.exec(
        'INSERT OR REPLACE INTO flue_sessions (id, data, updated_at) VALUES (?, ?, ?)',
        id, json, Date.now()
      );
    },
    async load(id) {
      const rows = sql.exec('SELECT data FROM flue_sessions WHERE id = ?', id).toArray();
      if (rows.length === 0) return null;
      return JSON.parse(rows[0].data);
    },
    async delete(id) {
      sql.exec('DELETE FROM flue_sessions WHERE id = ?', id);
    },
  };
}

function createContextForRequest(id, runId, payload, doInstance, req) {
  // Use DO SQLite storage by default, fall back to in-memory
  const defaultStore = doInstance?.ctx?.storage?.sql
    ? createDOStore(doInstance.ctx.storage.sql)
    : memoryStore;

  return createFlueContext({
    id,
    runId,
    payload,
    env: doInstance?.env ?? {},
    req,
    agentConfig: {
      systemPrompt, skills, roles, model: undefined, resolveModel,
    },
    createDefaultEnv,
    defaultStore,
    resolveSandbox,
  });
}

function createRunStoreForRequest(doInstance) {
  return doInstance?.ctx?.storage?.sql
    ? createDurableRunStore(doInstance.ctx.storage.sql)
    : memoryRunStore;
}

function createRunRegistryForRequest(reqEnv) {
  return createCloudflareRunRegistry(reqEnv?.FLUE_REGISTRY);
}

/**
 * Convert an agent name (URL segment, lower-kebab-case) back to its
 * Durable Object binding name (PascalCase). This MUST match the
 * build-time \`agentClassName\` helper byte-for-byte — its source is
 * inlined directly below via .toString() so the two cannot drift.
 * Used by the main worker to resolve a runId-derived target agent
 * back into a DO stub without keeping its own (name -> class) map.
 */
const agentBindingNameFromAgentName = ${agentClassName.toString().replace(/agentClassName/g, 'agentBindingNameFromAgentName')};

function runWithInstanceContext(doInstance, fn) {
  return runWithCloudflareContext(
    { env: doInstance.env, agentInstance: doInstance, storage: doInstance.ctx.storage },
    fn,
  );
}

function assertAgentsDurabilityApi(doInstance, method) {
  if (typeof doInstance[method] !== 'function') {
		throw new Error(
			'[flue] The installed "agents" package does not provide the required Cloudflare Agents SDK method "' +
				method +
				'". Install or upgrade the "agents" package in your project.',
		);
	}
}

async function handleFlueFiberRecovered(ctx, _doInstance, agentName) {
  if (!ctx.name || !ctx.name.startsWith('flue:')) return;
  console.warn('[flue] Cloudflare fiber interrupted:', agentName, ctx.name, ctx.snapshot ?? null);
}

// ─── Per-DO Dispatch ───────────────────────────────────────────────────────

async function dispatchAgent(request, doInstance, agentName, handler) {
  const id = doInstance.name; // DO room name set by routeAgentRequest
  const runRoute = parseRunRoute(request);
  if (runRoute) {
    return handleRunRouteRequest({
      request,
      agentName,
      id,
      runStore: createRunStoreForRequest(doInstance),
      runSubscribers,
      ...runRoute,
    });
  }

  return handleAgentRequest({
    request,
    agentName,
    id,
    handler,
    runStore: createRunStoreForRequest(doInstance),
    runSubscribers,
    runRegistry: createRunRegistryForRequest(doInstance.env),
    createContext: (id_, runId, payload, req) => createContextForRequest(id_, runId, payload, doInstance, req),
    startWebhook: (runId, run) => {
      const wrapped = (fiber) => {
        fiber?.stash?.({
          version: 1,
          kind: 'webhook',
          agentName,
          id,
          runId,
          phase: 'running',
          startedAt: Date.now(),
        });
        return runWithInstanceContext(doInstance, run);
      };
      assertAgentsDurabilityApi(doInstance, 'runFiber');
      return doInstance.runFiber('flue:webhook:' + runId, wrapped);
    },
    runHandler: (ctx, h) => runWithInstanceContext(doInstance, () => {
      assertAgentsDurabilityApi(doInstance, 'keepAliveWhile');
      return doInstance.keepAliveWhile(() => h(ctx));
    }),
  });
}

function parseRunRoute(request) {
  const segments = new URL(request.url).pathname.split('/').filter(Boolean);
  if (segments.length < 2 || segments[0] !== 'runs') return null;
  const runId = segments[1];
  const child = segments[2];
  if (!runId) return null;
  if (!child) return { action: 'get', runId };
  if (child === 'events') return { action: 'events', runId };
  if (child === 'stream') return { action: 'stream', runId };
  return null;
}

// ─── Per-Agent Durable Object Classes ──────────────────────────────────────

${agentClasses}

export { FlueRegistry };

// ─── User-declared Sandbox re-exports ──────────────────────────────────────
// One line per DO binding in the user's wrangler.jsonc whose class_name
// ends with "Sandbox". Flue aliases the single \`Sandbox\` class shipped by
// \`@cloudflare/sandbox\` so each user-chosen class_name resolves at the
// bundle's top level. The binding + container image configuration is owned
// by the user's wrangler.jsonc.
${sandboxReExports}

// ─── Runtime seed ───────────────────────────────────────────────────────────

configureFlueRuntime({
  target: 'cloudflare',
  runtimeVersion: ${runtimeVersion},
  manifest: ${manifestJson},
  webhookAgents: webhookAgentNames,
  // Cloudflare deploys never run in local mode — the trigger-less agents
  // simply have no DO class to land in.
  allowNonWebhook: false,
  routeAgentRequest: (request, env) => routeAgentRequest(request, env),
  createRunRegistryForRequest,
  routeRunRequest: async (request, reqEnv, target) => {
    const bindingName = agentBindingNameFromAgentName(target.agentName);
    const binding = reqEnv?.[bindingName];
    if (!binding) return null;
    const stub = await getAgentByName(binding, target.instanceId);
    return stub.fetch(request);
  },
});

// ─── App composition ────────────────────────────────────────────────────────

${
	appEntry
		? `// User-supplied app.ts. Their default export owns the entire request
// pipeline — the worker just verifies a fetch method exists and pipes
// through. The default flue() handler is available for them to mount
// however they want; this file does not impose a composition.
const app = userApp;
if (!app || typeof app.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request, env, ctx) method.'
  );
}`
		: `// No app.ts: build the default app via @flue/runtime so the generated entry
// stays \`hono\`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts \`flue()\` at root
// and renders canonical Flue envelopes for unmatched paths.
const app = createDefaultFlueApp();`
}

export default {
  fetch(request, env, ctx) {
    return app.fetch(request, env, ctx);
  },
};
`;
	}

	async additionalOutputs(ctx: BuildContext): Promise<Record<string, string>> {
		const outputs: Record<string, string> = {};
		const webhookAgents = ctx.agents.filter((a) => a.triggers.webhook);

		// Per-agent DO bindings: one per webhook agent. Flue no longer forces a
		// `Sandbox` binding, container entry, or Dockerfile — users who want
		// container sandboxes declare those themselves in their own
		// wrangler.jsonc (preserved via the merge below). Flue only automates
		// the `export { Sandbox as ... }` re-export in the bundle (see
		// generateEntryPoint).
		const flueBindings = webhookAgents.map((a) => ({
			class_name: agentClassName(a.name),
			name: agentClassName(a.name),
		}));

		const FLUE_REGISTRY_BINDING = { name: 'FLUE_REGISTRY', class_name: 'FlueRegistry' };
		flueBindings.push(FLUE_REGISTRY_BINDING);
		const flueSqliteClasses = flueBindings.map((b) => b.class_name);

		// Read and validate the user's wrangler config (if any). User's file
		// lives at the project root and is never modified; the
		// composed output is written to dist/wrangler.jsonc. Wrangler's reader
		// normalizes relative paths (e.g. containers[].image) to absolute paths
		// against the user's config dir, so the merged file stays correct
		// after we write it to dist/.
		const { config: userConfig, path: userConfigPath } = await this.getUserConfig(
			ctx.root,
		);
		if (userConfigPath) {
			console.log(`[flue] Merging with user wrangler config: ${userConfigPath}`);
		}
		validateUserWranglerConfig(userConfig);

		// Compute the migrations Flue wants to add for net-new agent classes.
		// Cloudflare migration tags are immutable once deployed, so we emit
		// one tag per class — that lets every redeploy be a no-op for already
		// deployed classes and a single-tag append for the truly net-new ones.
		// Renames and deletes are the user's responsibility (manual entries
		// in their wrangler.jsonc); Flue never auto-emits destructive
		// migrations.
		const flueMigrations = computeFlueMigrations(flueSqliteClasses, userConfig.migrations);

		// Flue's contributions to the wrangler config. Everything else in the
		// user's wrangler.jsonc passes through untouched during merge.
		// `path.basename` rather than `split('/').pop()` so this works on
		// Windows too (native path separator there is `\`).
		const additions: FlueAdditions = {
			defaultName: path.basename(ctx.root) || 'flue-agents',
			// `_entry.bundled.js` is generated by `build()` after Flue rewrites
			// framework-owned skill imports. Wrangler performs the final target bundle.
			main: '_entry.bundled.js',
			doBindings: flueBindings,
			migrations: flueMigrations,
		};

		// Detect user-declared Sandbox bindings and verify the @cloudflare/sandbox
		// package is available before esbuild tries to resolve it. Log each
		// binding we've auto-wired so users can see what Flue did on their behalf.
		const sandboxClassNames = detectSandboxBindings(userConfig);
		if (sandboxClassNames.length > 0) {
			assertSandboxPackageInstalled(sandboxClassNames, ctx.root);
			for (const className of sandboxClassNames) {
				console.log(
					`[flue] Auto-wiring DO binding "${className}" to @cloudflare/sandbox's Sandbox class.`,
				);
			}
		}

		const merged = mergeFlueAdditions(userConfig, additions);

		// Strip wrangler-normalizer defaults that cause spurious warnings when
		// wrangler re-parses the file (notably `unsafe: {}`). See the function
		// doc for the full rationale. Mutates `merged` in place.
		stripNoisyWranglerDefaults(merged);

		// Always include the wrangler JSON schema reference if absent so the
		// generated file gets editor validation if someone opens it directly.
		if (typeof merged.$schema !== 'string') {
			merged.$schema = 'https://workers.cloudflare.com/schema/wrangler.json';
		}

		outputs['wrangler.jsonc'] = JSON.stringify(merged, null, 2);

		// Flue no longer emits a Dockerfile. Users who use container sandboxes
		// provide their own Dockerfile at whatever path their wrangler.jsonc's
		// `containers[].image` points to.

		// Side effect: write the wrangler deploy-redirect file at
		// <root>/.wrangler/deploy/config.json so `wrangler deploy` run from the
		// project root automatically picks up our generated
		// `<output>/wrangler.jsonc`. Only written if not already present,
		// to respect user intent. This lives outside the build output, so
		// it's handled here rather than through the additionalOutputs return
		// value (which writes relative to output).
		writeDeployRedirectIfMissing(ctx.root, ctx.output);

		return outputs;
	}
}

function agentVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'agent';
	return `handler_${readableName}_${index}`;
}

const CLOUDFLARE_AGENT_NAME_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

function validateCloudflareAgentNames(ctx: BuildContext): void {
	const invalidAgents = ctx.agents.filter((agent) => !CLOUDFLARE_AGENT_NAME_PATTERN.test(agent.name));
	if (invalidAgents.length === 0) return;

	const invalidList = invalidAgents
		.map((agent) => {
			const relPath = path.relative(ctx.root, agent.filePath);
			return `${relPath} (${agent.name})`;
		})
		.join(', ');

	throw new Error(
		`[flue] Cloudflare target requires agent filenames to use lower-kebab-case so ` +
			`Durable Object bindings route correctly. Invalid agent file(s): ${invalidList}. ` +
			`Rename them to match ${CLOUDFLARE_AGENT_NAME_PATTERN}.`,
	);
}

/**
 * Convert agent name to a PascalCase DO class name.
 * "hello" → "Hello", "with-cloudflare" → "WithCloudflare"
 *
 * routeAgentRequest() converts binding names to kebab-case for URL matching,
 * so "WithCloudflare" → "with-cloudflare" → URL /agents/with-cloudflare/:id
 */
function agentClassName(name: string): string {
	return name
		.split(/[-_]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}
