/** Node.js build plugin. Produces a server for workflow runs and agent interactions. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	// Node has no platform-provided bundler — esbuild is our final-output
	// step here, producing a single self-contained `dist/server.mjs`.
	bundle = 'esbuild' as const;

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, appEntry, channels, workflows } = ctx;
		const runtimeVersion = JSON.stringify(ctx.runtimeVersion);

		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import * as ${varName} from '${filePath}';`;
			})
			.join('\n');

		const workflowImports = workflows
			.map((workflow, index) => {
				const varName = workflowVarName(workflow.name, index);
				const filePath = workflow.filePath.replace(/\\/g, '/');
				return `import * as ${varName} from '${filePath}';`;
			})
			.join('\n');

		const agentModuleEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');
		const workflowModuleEntries = workflows
			.map((workflow, index) => `  ${JSON.stringify(workflow.name)}: ${workflowVarName(workflow.name, index)},`)
			.join('\n');
		const channelImports = channels
			.map((channel, index) => {
				const varName = channelVarName(channel.name, index);
				const filePath = channel.filePath.replace(/\\/g, '/');
				return `import * as ${varName} from '${filePath}';`;
			})
			.join('\n');
		const channelModuleEntries = channels
			.map((channel, index) => `  ${JSON.stringify(channel.name)}: ${channelVarName(channel.name, index)},`)
			.join('\n');

		// User-supplied app.ts (if any). The generated entry imports the user's
		// default export and dispatches all requests through `app.fetch`. When
		// no app.ts is present, the generated entry constructs a thin default
		// Hono that mounts `flue()` and renders canonical error envelopes.
		const userAppImport = appEntry ? `import userApp from '${appEntry.replace(/\\/g, '/')}';` : '';

		// All HTTP routing, SSE/webhook/sync mode handling, agent dispatch,
		// and error rendering live in @flue/runtime's runtime modules. The
		// generated entry's job is now narrow: import handlers, build the
		// runtime config, instantiate sandboxes, start the listener.
		return `
// Auto-generated by flue (target: node)
import { serve } from '@hono/node-server';
import { WebSocketServer } from 'ws';
import { createNodeWebSocketTransport } from '@flue/runtime/node';
import { Bash, InMemoryFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  InMemoryRunStore,
  InMemoryRunRegistry,
  createRunSubscriberRegistry,
  bashFactoryToSessionEnv,
  resolveModel,
  configureFlueRuntime,
  createDefaultFlueApp,
  createDirectAgentHandler,
  createAgentDispatchProcessor,
  InMemoryDispatchQueue,
} from '@flue/runtime/internal';
${agentImports}
${workflowImports}
${channelImports}
${userAppImport}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const systemPrompt = '';

function normalizeBuiltModules(agentModules, workflowModules, channelModules) {
  const manifest = { agents: [], workflows: [] };
  const directHandlers = {};
  const createdAgents = {};
  const dispatchAgentNames = new Map();
  const workflowHandlers = {};
  const websocketAgentHandlers = {};
  const websocketWorkflowHandlers = {};
  const agentRouteMiddleware = {};
  const agentWebSocketMiddleware = {};
  const workflowRouteMiddleware = {};
  const workflowWebSocketMiddleware = {};
  const channelApps = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueCreatedAgent !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export createAgent(...).');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Agent "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.websocket !== undefined && typeof mod.websocket !== 'function') throw new Error('[flue] Agent "' + name + '" websocket export must be a callable Hono middleware value.');
    const channels = normalizeChannelList(mod.channels, 'agent "' + name + '"');
    if (typeof mod.route === 'function') channels.http = true;
    if (typeof mod.websocket === 'function') channels.websocket = true;
    assertDirectChannels(channels, 'agent "' + name + '"');
    manifest.agents.push({ name, channels, created: true });
    createdAgents[name] = mod.default;
    const previousDispatchName = dispatchAgentNames.get(mod.default);
    if (previousDispatchName !== undefined) throw new Error('[flue] Agents "' + previousDispatchName + '" and "' + name + '" default-export the same created agent value. Use distinct createAgent(...) values for dispatchable agent modules.');
    dispatchAgentNames.set(mod.default, name);
    if (channels.http) directHandlers[name] = createDirectAgentHandler(mod.default);
    if (channels.websocket) websocketAgentHandlers[name] = createDirectAgentHandler(mod.default);
    if (typeof mod.route === 'function') agentRouteMiddleware[name] = mod.route;
    if (typeof mod.websocket === 'function') agentWebSocketMiddleware[name] = mod.websocket;
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    if (typeof mod.run !== 'function') throw new Error('[flue] Workflow "' + name + '" must export a callable run value.');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Workflow "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.websocket !== undefined && typeof mod.websocket !== 'function') throw new Error('[flue] Workflow "' + name + '" websocket export must be a callable Hono middleware value.');
    const channels = normalizeChannelList(mod.channels, 'workflow "' + name + '"');
    if (typeof mod.route === 'function') channels.http = true;
    if (typeof mod.websocket === 'function') channels.websocket = true;
    assertDirectChannels(channels, 'workflow "' + name + '"');
    manifest.workflows.push({ name, channels });
    if (channels.http) workflowHandlers[name] = mod.run;
    if (channels.websocket) websocketWorkflowHandlers[name] = mod.run;
    if (typeof mod.route === 'function') workflowRouteMiddleware[name] = mod.route;
    if (typeof mod.websocket === 'function') workflowWebSocketMiddleware[name] = mod.websocket;
  }

  for (const [name, mod] of Object.entries(channelModules)) {
    if (!mod.default || mod.default.__flueDefinedChannel !== true || typeof mod.default.on !== 'function' || typeof mod.default.emit !== 'function') {
      throw new Error('[flue] Channel "' + name + '" must default-export defineChannel({ app }).');
    }
    if (mod.default.app !== undefined) {
      if (!mod.default.app || typeof mod.default.app.fetch !== 'function') throw new Error('[flue] Channel "' + name + '" app must be a Hono application with a fetch method.');
      channelApps[name] = mod.default.app;
    }
  }

  return { manifest, directHandlers, createdAgents, dispatchAgentNames, workflowHandlers, websocketAgentHandlers, websocketWorkflowHandlers, agentRouteMiddleware, agentWebSocketMiddleware, workflowRouteMiddleware, workflowWebSocketMiddleware, channelApps };
}

function normalizeChannelList(value, label) {
  if (value === undefined) return {};
  if (!Array.isArray(value)) throw new Error('[flue] channels export for ' + label + ' must be an array.');
  const result = {};
  for (const entry of value) {
    const definition = normalizeChannelExport(entry, label + ' channel');
    result[definition.name] = true;
  }
  return result;
}

function normalizeChannelExport(value, label) {
  const definition = typeof value === 'function' ? value() : value;
  if (!definition || typeof definition !== 'object' || definition.__flueChannel !== true || typeof definition.name !== 'string' || definition.name.trim() === '') {
    throw new Error('[flue] Invalid ' + label + ': expected a channel definition or zero-argument channel factory.');
  }
  return definition;
}

function assertDirectChannels(channels, label) {
  for (const channel of Object.keys(channels)) {
    if (channel !== 'http' && channel !== 'websocket') {
      throw new Error('[flue] ' + label + ' has unsupported attached channel "' + channel + '". Only http() and websocket() are supported.');
    }
  }
}

const agentModules = {
${agentModuleEntries}
};
const workflowModules = {
${workflowModuleEntries}
};
const channelModules = {
${channelModuleEntries}
};
const normalized = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const { manifest, directHandlers, createdAgents, dispatchAgentNames, workflowHandlers, websocketAgentHandlers, websocketWorkflowHandlers, agentRouteMiddleware, agentWebSocketMiddleware, workflowRouteMiddleware, workflowWebSocketMiddleware, channelApps } = normalized;

// When the CLI starts this server via \`flue run\`, it sets FLUE_MODE=local.
const isLocalMode = process.env.FLUE_MODE === 'local';

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();
const runStore = new InMemoryRunStore();
const runRegistry = new InMemoryRunRegistry();
const runSubscribers = createRunSubscriberRegistry();
const dispatchQueue = new InMemoryDispatchQueue(createAgentDispatchProcessor({
  agents: createdAgents,
  createContext: createContextForRequest,
}));

function createContextForRequest(id, runId, payload, req) {
  return createFlueContext({
    id,
    runId,
    payload,
    env: process.env,
    req,
    agentConfig: {
      systemPrompt, skills, model: undefined, resolveModel,
    },
    createDefaultEnv,
    defaultStore,
  });
}

// ─── Runtime seed ───────────────────────────────────────────────────────────

const websocketTransport = createNodeWebSocketTransport({
  manifest,
  agentHandlers: websocketAgentHandlers,
  workflowHandlers: websocketWorkflowHandlers,
  createContext: createContextForRequest,
  runStore,
  runSubscribers,
  runRegistry,
});

// Seed the public flue() sub-app with everything it needs to dispatch agent
// requests in-process. Must run before \`flue()\` handles any request — by
// virtue of being a top-level statement, it executes before \`serve(...)\`
// below binds the listener. User app.ts files that call \`flue()\` at top
// level are also fine because Hono routes are lazy: they read this config
// only when a request arrives.
configureFlueRuntime({
  target: 'node',
  runtimeVersion: ${runtimeVersion},
  manifest,
  handlers: directHandlers,
  dispatchQueue,
  resolveDispatchAgentName: (agent) => dispatchAgentNames.get(agent),
  workflowHandlers,
  agentRouteMiddleware,
  agentWebSocketMiddleware,
  workflowRouteMiddleware,
  workflowWebSocketMiddleware,
  channelApps,
  nodeWebSocketAgentRoute: websocketTransport.agentRoute,
  nodeWebSocketWorkflowRoute: websocketTransport.workflowRoute,
  createContext: createContextForRequest,
  runStore,
  runSubscribers,
  runRegistry,
});

// ─── App composition ────────────────────────────────────────────────────────

${
	appEntry
		? `// User-supplied app.ts: their default export owns the entire request
// pipeline. We just verify it exposes a fetch method and pass the
// listener through. flue() is available for them to mount, but the
// composition is theirs to author.
const app = userApp;
if (!app || typeof app.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request) method.'
  );
}`
		: `// No app.ts: build the default app via @flue/runtime so the generated entry
// stays \`hono\`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts \`flue()\` at root
// and renders canonical Flue envelopes for unmatched paths.
const app = createDefaultFlueApp();`
}

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({
  fetch: app.fetch,
  websocket: { server: websocketTransport.server },
  port,
  // SSE requests can outlive Node's default 300s request timeout.
  serverOptions: { requestTimeout: 0 },
});
console.log('[flue] Server listening on http://localhost:' + port);
if (isLocalMode) {
	console.log('[flue] Mode: local');
	console.log('[flue] Agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
} else {
	console.log('[flue] Agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
}

async function stop() {
  await websocketTransport.close();
  server.close();
  process.exit(0);
}
process.on('SIGINT', () => { void stop(); });
process.on('SIGTERM', () => { void stop(); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
			banner: { js: `import { createRequire as __flueCreateRequire } from 'node:module'; const require = __flueCreateRequire(import.meta.url);` },
			// just-bash's archive code wraps these native addons in dynamic imports
			// inside try/catch and declares them as optionalDependencies. Externalize
			// so esbuild doesn't try to resolve them at bundle time — the failure
			// path is handled by just-bash at runtime with a clear error message.
			external: ['node-liblzma', '@mongodb-js/zstd'],
		};
	}
}

function agentVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'agent';
	return `handler_${readableName}_${index}`;
}

function workflowVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'workflow';
	return `workflow_${readableName}_${index}`;
}

function channelVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'channel';
	return `channel_${readableName}_${index}`;
}
